version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "Dino-Kupinic"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    assignees:
      - "Dino-Kupinic"
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
    assignees:
      - "Dino-Kupinic"
  - package-ecosystem: "composer"
    directory: "/backend"
    schedule:
      interval: "weekly"
    assignees:
      - "Dino-Kupinic"
