services:
  nuxt-nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nuxt-nginx
    ports:
      - "3001:3001"
    environment:
      - BACKEND_API=http://localhost:8000/api/v1
