version: '3'

services:
  db:
    image: mysql:latest
    ports:
      - "${BIND_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SECRET_PASSWORD}
      MYSQL_DATABASE: schulbuchaktion
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${SECRET_PASSWORD}

  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    hostname: openldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./data/certificates:/container/service/slapd/assets/certs
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=schulbuchaktion
      - LDAP_DOMAIN=schulbuchaktion.env
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=password
      - LDAP_CONFIG_PASSWORD=config_pass
      - "LDAP_BASE_DN=dc=schulbuchaktion,dc=env"
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=schulbuchaktion.env.ca.crt
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=testuser
      - LDAP_READONLY_USER_PASSWORD=aaaAAA123
    networks:
      - openldap

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports:
      - "80:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - openldap

volumes:
  mysql_data:

networks:
  openldap:
    driver: bridge
