services:
  db:
    image: mysql:latest
    container_name: 'mysql_db'
    ports:
      - "${BIND_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/db/data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${SECRET_PASSWORD}
      MYSQL_DATABASE: schulbuchaktion
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${SECRET_PASSWORD}

  php:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ${IMAGES_PREFIX:-}backend_php
    container_name: backend_php
    restart: unless-stopped
    environment:
      APP_ENV: ${APP_ENV}
      SERVER_NAME: ${SERVER_NAME}, php:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES}
      TRUSTED_HOSTS: ${TRUSTED_HOSTS}
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      DATABASE_URL: ${DATABASE_URL}
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_URL: ${CADDY_MERCURE_URL}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET}
      # The two next lines can be removed after initial installation
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./:/app:rw

    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT}
        protocol: tcp

  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    hostname: openldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./docker/data/certificates:/container/service/slapd/assets/certs
      - ./docker/data/slapd/database:/var/lib/ldap
      - ./docker/data/slapd/config:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=schulbuchaktion
      - LDAP_DOMAIN=schulbuchaktion.env
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=password
      - LDAP_CONFIG_PASSWORD=config_pass
      - "LDAP_BASE_DN=dc=schulbuchaktion,dc=env"
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=schulbuchaktion.env.ca.crt
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=testuser
      - LDAP_READONLY_USER_PASSWORD=aaaAAA123
    networks:
      - openldap

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports:
      - "8080:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - openldap

volumes:
  mysql_data:
  caddy_data:
  caddy_config:

networks:
  openldap:
    driver: bridge
