nelmio_api_doc:
    use_validation_groups: true
    documentation:
        info:
            title: Schulbuchaktion API
    areas: # to filter documented areas
        path_patterns:
            - ^/api # Accepts routes under /api
